#!/usr/bin/env bash
# Usage: manage prepare
# Summary: Prepare environment
# Help: This command is used to prepare the environment for the container.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

if [ -n "${HAPROXY_CERT}" ]
then
  if [ -f $HAPROXY_CERT ]
  then
    cat "${HAPROXY_CERT}" >| /etc/ssl/private/haproxy.pem
  else
    echo -e "${HAPROXY_CERT}" >| /etc/ssl/private/haproxy.pem
  fi
fi
