#!/usr/bin/env bash
# Usage: manage check [file]
# Summary: Check config file
# Help: This command is used to check the config file of the service.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

[ "$1" = "" ] && CONFIG_FILE=/etc/haproxy/haproxy.cfg || CONFIG_FILE=$1

/usr/sbin/haproxy -q -c -f $CONFIG_FILE
