#!/usr/bin/env bash
# Usage: manage start
# Summary: Start the main process
# Help: This command is used to start the main process.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

if manage-running
then
  echo "Service is already running"
else
  manage-prepare && start-stop-daemon --pidfile /var/run/haproxy.pid --exec /usr/sbin/haproxy --start -- -D -p /var/run/haproxy.pid -f /etc/haproxy/haproxy.cfg

  case "${DISCOVERY_TYPE}" in
    etcd)
      DISCOVERY_COMMAND="confd -backend etcd -node ${DISCOVERY_HOST}:${DISCOVERY_PORT} -prefix ${DISCOVERY_PREFIX}"

      if [ -n "${DISCOVERY_CLIENT_KEY}" ]
      then
        if [ -f "${DISCOVERY_CLIENT_KEY}" ]
        then
          DISCOVERY_COMMAND="${DISCOVERY_COMMAND} -client-key=${DISCOVERY_CLIENT_KEY}"
        else
          echo -e "${DISCOVERY_CLIENT_KEY}" >| /tmp/etcd.key
          DISCOVERY_COMMAND="${DISCOVERY_COMMAND} -client-key=/tmp/etcd.key"
        fi
      fi

      if [ -n "${DISCOVERY_CLIENT_CERT}" ]
      then
        if [ -f "${DISCOVERY_CLIENT_CERT}" ]
        then
          DISCOVERY_COMMAND="${DISCOVERY_COMMAND} -client-cert=${DISCOVERY_CLIENT_CERT}"
        else
          echo -e "${DISCOVERY_CLIENT_CERT}" >| /tmp/etcd.crt
          DISCOVERY_COMMAND="${DISCOVERY_COMMAND} -client-cert=/tmp/etcd.crt"
        fi
      fi

      if [ -n "${DISCOVERY_CLIENT_CA}" ]
      then
        if [ -f "${DISCOVERY_CLIENT_CA}" ]
        then
          DISCOVERY_COMMAND="${DISCOVERY_COMMAND} -client-cert=${DISCOVERY_CLIENT_CA}"
        else
          echo -e "${DISCOVERY_CLIENT_CA}" >| /tmp/ca.crt
          DISCOVERY_COMMAND="${DISCOVERY_COMMAND} -client-ca-keys=/tmp/ca.crt"
        fi
      fi

      DISCOVERY_COMMAND="${DISCOVERY_COMMAND} ${DISCOVERY_OPTS}"
      ;;
    consul)
      DISCOVERY_COMMAND="confd -backend consul -node ${DISCOVERY_HOST}:${DISCOVERY_PORT} -prefix ${DISCOVERY_PREFIX} ${DISCOVERY_OPTS}"
      ;;
    env)
      DISCOVERY_COMMAND="confd -backend env -prefix ${DISCOVERY_PREFIX} ${DISCOVERY_OPTS}"
      ;;
  esac

  echo "Loading initial config..."
  until ${DISCOVERY_COMMAND} -onetime
  do
    sleep 10
  done

  echo "Running confd constant..."
  ${DISCOVERY_COMMAND} -interval ${DISCOVERY_INTERVAL} -quiet
fi
